# Generated by Django 4.2.2 on 2023-08-26 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_user_followed_remove_user_followers_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('Liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liker', to=settings.AUTH_USER_MODEL)),
                ('Post_Liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='network.post')),
            ],
        ),
    ]
